/* Automatically generated by po2tbl.sed from xchat.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Cannot create ~/.xchat", 2},
  {"\
The default download directory is your\n\
home dir, you should change this at some stage.", 3},
  {"\
* Running IRC as root is stupid! You should\n\
  create a User Account and use that to login.\n\
\n\
* The default download directory is your\n\
  home dir, you should change this at some stage.", 4},
  {"I'm busy", 5},
  {"Client Exiting", 6},
  {"Waiting", 7},
  {"Active", 8},
  {"Failed", 9},
  {"Done", 10},
  {"Connect", 11},
  {"Aborted", 12},
  {"Cannot access %s\n", 13},
  {"No active DCCs\n", 14},
  {"YES  ", 15},
  {"NO   ", 16},
  {"  %-20s online\n", 17},
  {"  %-20s offline\n", 18},
  {"No channel joined. Try /join #<channel>\n", 19},
  {"Not connected. Try /server <host> [<port>]\n", 20},
  {"/ADDBUTTON <name> <action>, adds a button under the user-list\n", 21},
  {"/ALLCHAN <cmd>, sends a command to all channels you're in\n", 22},
  {"/ALLSERV <cmd>, sends a command to all servers you're in\n", 23},
  {"/AWAY [<reason>], sets you away\n", 24},
  {"\
/BAN <mask> [<bantype>], bans everyone matching the mask from the current \
channel. If they are already on the channel this doesn't kick them (needs \
chanop)\n", 25},
  {"/UNBAN <mask> [<mask>...], unbans the specified masks.\n", 26},
  {"/CLEAR, Clears the current text window\n", 27},
  {"/CLOSE, Closes the current window/tab\n", 28},
  {"\
/CTCP <nick> <message>, send the CTCP message to nick, common messages are \
VERSION and USERINFO\n", 29},
  {"/COUNTRY <code>, finds a country code, eg: au = australia\n", 30},
  {"/CYCLE, parts current channel and immediately rejoins\n", 31},
  {"\
\n\
/DCC GET <nick>          - receive an offered file\n\
/DCC SEND <nick> <file>  - send a file to someone\n\
/DCC LIST                - show DCC list\n\
/DCC CHAT <nick>         - offer DCC CHAT to someone\n\
/DCC CLOSE <type> <nick> <file>         example:\n\
         /dcc close send johnsmith file.tar.gz\n", 32},
  {"/DELBUTTON <name>, deletes a button from under the user-list\n", 33},
  {"\
/DEHOP <nick>, removes chanhalf-op status from the nick on the current \
channel (needs chanop)\n", 34},
  {"\
/DEOP <nick>, removes chanop status from the nick on the current channel \
(needs chanop)\n", 35},
  {"\
/DEVOICE <nick>, removes voice status from the nick on the current channel \
(needs chanop)\n", 36},
  {"/DISCON, Disconnects from server\n", 37},
  {"/DNS <nick|host|ip>, Finds a users IP number\n", 38},
  {"/ECHO <text>, Prints text locally\n", 39},
  {"\
/EXEC [-o] <command>, runs the command. If -o flag is used then output is \
sent to current channel, else is printed to current text box\n", 40},
  {"\
/EXECKILL [-9], kills a running exec in the current session. If -9 is given \
the process is SIGKILL'ed\n", 41},
  {"/EXECSTOP, sends the process SIGSTOP\n", 42},
  {"/EXECCONT, sends the process SIGCONT\n", 43},
  {"/EXECWRITE, sends data to the processes stdin\n", 44},
  {"/FLUSHQ, flushes the current server's send queue\n", 45},
  {"/GATE <host> [<port>], proxies through a host, port defaults to 23\n", 46},
  {"/HOP <nick>, gives chanhalf-op status to the nick (needs chanop)\n", 47},
  {"\
/IGNORE <mask> <types..> <options..>\n\
    mask - host mask to ignore, eg: *!*@*.aol.com\n\
    types - types of data to ignore, one or all of:\n\
            PRIV, CHAN, NOTI, CTCP, INVI, ALL\n\
    options - NOSAVE, QUIET\n", 48},
  {"\
/INVITE <nick> [<channel>], invites someone to a channel, by default the \
current channel (needs chanop)\n", 49},
  {"/JOIN <channel>, joins the channel\n", 50},
  {"/KICK <nick>, kicks the nick from the current channel (needs chanop)\n", 51},
  {"\
/KICKBAN <nick>, bans then kicks the nick from the current channel (needs \
chanop)\n", 52},
  {"/LAGCHECK, forces a new lag check\n", 53},
  {"/LASTLOG <string>, searches for a string in the buffer.\n", 54},
  {"/LISTDLL, Lists all currenly loaded plugins\n", 55},
  {"/LOAD <file>, loads a Perl script\n", 56},
  {"/LOADDLL <file>, loads a plugin\n", 57},
  {"\
/MDEHOP, Mass deop's all chanhalf-ops in the current channel (needs chanop)\n", 58},
  {"/MDEOP, Mass deop's all chanops in the current channel (needs chanop)\n", 59},
  {"\
/MKICK, Mass kicks everyone except you in the current channel (needs \
chanop)\n", 60},
  {"\
/MKICKB, Sets a ban of *@* and mass kicks everyone except you in the current \
channel (needs chanop)\n", 61},
  {"\
/ME <action>, sends the action to the current channel (actions are written \
in the 3rd person, like /me jumps)\n", 62},
  {"/MSG <nick> <message>, sends a private message\n", 63},
  {"/NAMES, Lists the nicks on the current channel\n", 64},
  {"/NCTCP <nick> <message>, Sends a CTCP notice\n", 65},
  {"/NEWSERVER <hostname> [<port>]\n", 66},
  {"/NICK <nickname>, sets your nick\n", 67},
  {"\
/NOTICE <nick/channel> <message>, sends a notice. Notices are a type of \
message that should be auto reacted to\n", 68},
  {"/NOTIFY [<nick>], lists your notify list or adds someone to it\n", 69},
  {"/OP <nick>, gives chanop status to the nick (needs chanop)\n", 70},
  {"\
/PART [<channel>] [<reason>], leaves the channel, by default the current \
one\n", 71},
  {"/PING <nick | channel>, CTCP pings nick or channel\n", 72},
  {"/PKILL <name>, kills the script of the given name\n", 73},
  {"/PLIST, lists the current python scripts\n", 74},
  {"/PLOAD loads a python script\n", 75},
  {"/QUERY <nick>, opens up a new privmsg window to someone\n", 76},
  {"/QUIT [<reason>], disconnects from the current server\n", 77},
  {"/QUOTE <text>, sends the text in raw form to the server\n", 78},
  {"\
/RECONNECT [-ssl] [<host>] [<port>] [<password>], Can be called just as /\
RECONNECT to reconnect to the current server or with /RECONNECT ALL to \
reconnect to all the open servers\n", 79},
  {"\
/RECONNECT [<host>] [<port>] [<password>], Can be called just as /RECONNECT \
to reconnect to the current server or with /RECONNECT ALL to reconnect to \
all the open servers\n", 80},
  {"/RMDLL <dll name>, unloads a plugin\n", 81},
  {"/SAY <text>, sends the text to the object in the current window\n", 82},
  {"/SCPINFO, Lists some information about current Perl bindings\n", 83},
  {"/SET <variable> [<value>]\n", 84},
  {"\
/SERVCHAN [-ssl] <host> <port> <channel>, connects and joins a channel\n", 85},
  {"/SERVCHAN <host> <port> <channel>, connects and joins a channel\n", 86},
  {"\
/SERVER [-ssl] <host> [<port>] [<password>], connects to a server, the \
default port is 6667 for normal connections, and 994 for ssl connections.\n", 87},
  {"\
/SERVER <host> [<port>] [<password>], connects to a server, the default port \
is 6667.\n", 88},
  {"/TIMER <seconds> <command>\n", 89},
  {"\
/TOPIC [<topic>], sets the topic if one is given, else shows the current \
topic\n", 90},
  {"/UNIGNORE <mask> [QUIET]\n", 91},
  {"/UNLOADALL, Unloads all perl scripts\n", 92},
  {"\
/WALLCHOP <message>, sends the message to all chanops on the current \
channel\n", 93},
  {"/WALLCHAN <message>, writes the message to all channels\n", 94},
  {"/VOICE <nick>, gives voice status to someone (needs chanop)\n", 95},
  {"Usage:\n", 96},
  {"\
\n\
No help available on that command.\n", 97},
  {"No such command.\n", 98},
  {"I need /bin/sh to run!\n", 99},
  {"\
\n\
Commands Available:\n\
\n\
  ", 100},
  {"\
\n\
\n\
Type /HELP <command> for more information, or /HELP -l\n\
\n", 101},
  {"\
User defined commands:\n\
\n\
  ", 102},
  {"Unknown arg '%s' ignored.", 103},
  {"Error compiling script\n", 104},
  {"Error Loading file\n", 105},
  {"Perl scripting not available in this compilation.\n", 106},
  {"Bad arguments for user command.\n", 107},
  {"Too many recursive usercommands, aborting.", 108},
  {"Unknown Command. Try /help\n", 109},
  {"Registered Scripts:\n", 110},
  {"Inbound Handlers:\n", 111},
  {"Command Handlers:\n", 112},
  {"Print Handlers:\n", 113},
  {"**** ENDING LOGGING AT %s\n", 114},
  {"**** BEGIN LOGGING AT %s\n", 115},
  {"The nick of the joining person", 116},
  {"The channel being joined", 117},
  {"The host of the person", 118},
  {"Nickname", 119},
  {"The action", 120},
  {"The text", 121},
  {"Mode char", 122},
  {"The message", 123},
  {"Old nickname", 124},
  {"New nickname", 125},
  {"Nick of person who changed the topic", 126},
  {"Topic", 127},
  {"Channel", 128},
  {"The nickname of the kicker", 129},
  {"The person being kicked", 130},
  {"The channel", 131},
  {"The reason", 132},
  {"The nick of the person leaving", 133},
  {"The time", 134},
  {"The creator", 135},
  {"Nick", 136},
  {"Reason", 137},
  {"Host", 138},
  {"Who it's from", 139},
  {"The time in x.x format (see below)", 140},
  {"The Channel it's going to", 141},
  {"The sound", 142},
  {"The nick of the person", 143},
  {"The CTCP event", 144},
  {"The nick of the person who set the key", 145},
  {"The key", 146},
  {"The nick of the person who set the limit", 147},
  {"The limit", 148},
  {"The nick of the person who did the op'ing", 149},
  {"The nick of the person who has been op'ed", 150},
  {"The nick of the person who did the halfop'ing", 151},
  {"The nick of the person who has been halfop'ed", 152},
  {"The nick of the person who did the voice'ing", 153},
  {"The nick of the person who has been voice'ed", 154},
  {"The nick of the person who did the banning", 155},
  {"The ban mask", 156},
  {"The nick who removed the key", 157},
  {"The nick who removed the limit", 158},
  {"The nick of the person of did the deop'ing", 159},
  {"The nick of the person who has been deop'ed", 160},
  {"The nick of the person of did the dehalfop'ing", 161},
  {"The nick of the person who has been dehalfop'ed", 162},
  {"The nick of the person of did the devoice'ing", 163},
  {"The nick of the person who has been devoice'ed", 164},
  {"The nick of the person of did the unban'ing", 165},
  {"The nick of the person who did the exempt", 166},
  {"The exempt mask", 167},
  {"The nick of the person removed the exempt", 168},
  {"The nick of the person who did the invite", 169},
  {"The invite mask", 170},
  {"The nick of the person removed the invite", 171},
  {"The nick of the person setting the mode", 172},
  {"The mode's sign (+/-)", 173},
  {"The mode letter", 174},
  {"The channel it's being set on", 175},
  {"Username", 176},
  {"Full name", 177},
  {"Channel Membership/\"is an IRC operator\"", 178},
  {"Server Information", 179},
  {"Idle time", 180},
  {"Signon time", 181},
  {"Away reason", 182},
  {"Channel Name", 183},
  {"Text", 184},
  {"Nick of person who invited you", 185},
  {"Server Name", 186},
  {"Users", 187},
  {"Nickname in use", 188},
  {"Nick being tried", 189},
  {"Error String", 190},
  {"IP", 191},
  {"Port", 192},
  {"PID", 193},
  {"Channel name", 194},
  {"Modes string", 195},
  {"IP address", 196},
  {"port", 197},
  {"DCC Type", 198},
  {"Filename", 199},
  {"Destination filename", 200},
  {"CPS", 201},
  {"Error string", 202},
  {"{to|from}", 203},
  {"DCC type", 204},
  {"Position", 205},
  {"Size", 206},
  {"DCC String", 207},
  {"Number of notify items", 208},
  {"Servername", 209},
  {"Old Filename", 210},
  {"New Filename", 211},
  {"Receiver", 212},
  {"Message", 213},
  {"Hostmask", 214},
  {"Priv Yes/No", 215},
  {"Noti Yes/No", 216},
  {"Chan Yes/No", 217},
  {"Ctcp Yes/No", 218},
  {"Invi Yes/No", 219},
  {"Unig Yes/No", 220},
  {"Hostname", 221},
  {"The Packet", 222},
  {"Number of messages", 223},
  {"Bytes in mailbox", 224},
  {"Seconds", 225},
  {"Nick of person who have been invited", 226},
  {"Banmask", 227},
  {"Who set the ban", 228},
  {"Ban time", 229},
  {"Error", 230},
  {"-%C10-%C11>%O$t%B$1%B %C14(%C10$3%C14)%C has joined $2", 231},
  {"%C13*%O$t$1 $2%O", 232},
  {"%C13*%O$t%C8%B$1%B%O $2%O", 233},
  {"%C2<%O$1%C2>%O$t$2%O", 234},
  {"%C2<%C8%B$1%B%C2>%O$t$2%O", 235},
  {"%C12*%C13$1%C12*$t%O$2%O", 236},
  {"-%C10-%C11-%O$t$1 is now known as $2", 237},
  {"-%C10-%C11-%O$t$1 has changed the topic to: $2%O", 238},
  {"-%C10-%C11-%O$tTopic for %C11$1%C is %C11$2%O", 239},
  {"<%C10-%C11-%O$t$1 has kicked $2 from $3 ($4%O)", 240},
  {"<%C10-%C11-%O$t$1 %C14(%O$2%C14)%C has left $3", 241},
  {"-%C10-%C11-%O$tChannel $1 created on $2", 242},
  {"-%C10-%C11-%O$tTopic for %C11$1%C set by %C11$2%C at %C11$3%O", 243},
  {"<%C10-%C11-%O$t$1 has quit %C14(%O$2%O%C14)%O", 244},
  {"-%C10-%C11-%O$tPing reply from $1 : $2 second(s)", 245},
  {"%C12-%C13$1%C12-%O$t$2%O", 246},
  {"-%C10-%C11>%O$t%BYou%B are now talking on %C11$2%O", 247},
  {"%C6<%O$1%C6>%O$t$2%O", 248},
  {"-%C10-%C11-%O$tYou are now known as $2", 249},
  {"-%C10-%C11-%O$tYou have been kicked from $2 by $3 ($4%O)", 250},
  {"-%C10-%C11-%O$tYou have left channel $3", 251},
  {"-%C10-%C11-%O$tReceived a CTCP Sound $1 from $2", 252},
  {"-%C10-%C11-%O$tReceived a CTCP $1 from $2", 253},
  {"-%C10-%C11-%O$tReceived a CTCP $1 from $2 (to $3)", 254},
  {"-%C10-%C11-%O$t$1 sets channel keyword to $2", 255},
  {"-%C10-%C11-%O$t$1 sets channel limit to $2", 256},
  {"-%C10-%C11-%O$t$1 gives channel half-operator status to $2", 257},
  {"-%C10-%C11-%O$t$1 gives channel operator status to $2", 258},
  {"-%C10-%C11-%O$t$1 gives voice to $2", 259},
  {"-%C10-%C11-%O$t$1 sets ban on $2", 260},
  {"-%C10-%C11-%O$t$1 removes channel keyword", 261},
  {"-%C10-%C11-%O$t$1 removes user limit", 262},
  {"-%C10-%C11-%O$t$1 removes channel half-operator status from $2", 263},
  {"-%C10-%C11-%O$t$1 removes channel operator status from $2", 264},
  {"-%C10-%C11-%O$t$1 removes voice from $2", 265},
  {"-%C10-%C11-%O$t$1 removes ban on $2", 266},
  {"-%C10-%C11-%O$t$1 sets exempt on $2", 267},
  {"-%C10-%C11-%O$t$1 removes exempt on $2", 268},
  {"-%C10-%C11-%O$t$1 sets invite on $2", 269},
  {"-%C10-%C11-%O$t$1 removes invite on $2", 270},
  {"-%C10-%C11-%O$t$1 sets mode $2$3 $4", 271},
  {"-%C10-%C11-%O$t%C12[%O$1%C12] %C14(%O$2@$3%C14) %O: $4%O", 272},
  {"-%C10-%C11-%O$t%C12[%O$1%C12]%C $2", 273},
  {"-%C10-%C11-%O$t%C12[%O$1%C12]%O $2", 274},
  {"-%C10-%C11-%O$t%C12[%O$1%C12]%O idle %C11$2%O", 275},
  {"-%C10-%C11-%O$t%C12[%O$1%C12]%O idle %C11$2%O, signon: %C11$3%O", 276},
  {"-%C10-%C11-%O$t%C12[%O$1%C12] %Cis away %C14(%O$2%O%C14)", 277},
  {"-%C10-%C11-%O$t%C12[%O$1%C12] %CEnd of WHOIS list.", 278},
  {"-%C10-%C11-%O$tCannot join%C11 %B$1 %O(User limit reached).", 279},
  {"-%C10-%C11-%O$tCannot join%C11 %B$1 %O(You are banned).", 280},
  {"-%C10-%C11-%O$tCannot join%C11 %B$1 %O(Channel is invite only).", 281},
  {"-%C10-%C11-%O$tCannot join%C11 %B$1 %O(Requires keyword).", 282},
  {"-%C10-%C11-%O$tMOTD Skipped.", 283},
  {"-%C10-%C11-%O$t$1%O", 284},
  {"-%C10-%C11-%O$tYou have been invited to %C11$1%C by %C11$2%C (%C11$3%C)", 285},
  {"-%C10-%C11-%O$t%C11Users on $1:%C $2", 286},
  {"-%C10-%C11-%O$t$1 already in use. Retrying with $2..", 287},
  {"-%C10-%C11-%O$tNickname already in use. Use /NICK to try another.", 288},
  {"-%C10-%C11-%O$tUnknown host. Maybe you misspelled it?", 289},
  {"-%C10-%C11-%O$tConnection failed. Error: $1", 290},
  {"-%C10-%C11-%O$tConnecting to %C11$1 %C14(%C11$2%C14)%C port %C11$3%C..", 291},
  {"-%C10-%C11-%O$tConnected. Now logging in..", 292},
  {"-%C10-%C11-%O$tStopped previous connection attempt (pid=$1)", 293},
  {"-%C10-%C11-%O$tDisconnected ($1).", 294},
  {"-%C10-%C11-%O$tNo such DCC.", 295},
  {"-%C10-%C11-%O$t$1 deleted from notify list.", 296},
  {"-%C10-%C11-%O$t$1 added to notify list.", 297},
  {"-%C10-%C11-%O$tChannel $1 modes: $2", 298},
  {"-%C10-%C11-%O$t$1 sets modes%B %C14[%O$2%B%C14]%O", 299},
  {"-%C10-%C11-%O$tYou have been killed by $1 ($2%O)", 300},
  {"-%C10-%C11-%O$tDCC $1 %C11$2 %Cto %C11$3 %Cstalled - aborting.", 301},
  {"-%C10-%C11-%O$tDCC $1 %C11$2 %Cto %C11$3 %Ctimed out - aborting.", 302},
  {"\
-%C10-%C11-%O$tDCC CHAT failed. Connection to $1 %C14[%O$2:$3%C14]%O lost.", 303},
  {"-%C10-%C11-%O$tDCC RECV: Cannot open $1 for writing - aborting.", 304},
  {"-%C10-%C11-%O$tDCC RECV $1 ($2) failed. Connection to $3 lost.", 305},
  {"\
-%C10-%C11-%O$tDCC RECV %C11$1%O from %C11$3%O complete %C14[%C11$4%O cps%\
C14]%O.", 306},
  {"-%C10-%C11-%O$tDCC $1 connect attempt to %C11$2%O failed (err=$3).", 307},
  {"-%C10-%C11-%O$tDCC $1 connection established $4 %C11$2 %C14[%O$3%C14]%O", 308},
  {"-%C10-%C11-%O$tDCC SEND %C11$1%O failed. Connection to %C11$2%O lost.", 309},
  {"\
-%C10-%C11-%O$tDCC SEND %C11$1%O to %C11$2%O complete %C14[%C11$3%O cps%C14]%\
O.", 310},
  {"-%C10-%C11-%O$tOffering %C11$1 %Cto %C11$2%O", 311},
  {"-%C10-%C11-%O$tDCC $1 %C11$2 %Cto %C11$3 %Caborted.", 312},
  {"-%C10-%C11-%O$tNo such DCC offer.", 313},
  {"-%C10-%C11-%O$tAlready offering CHAT to $1", 314},
  {"-%C10-%C11-%O$tOffering DCC CHAT to $1", 315},
  {"-%C10-%C11-%O$tReceived a DCC CHAT offer from $1", 316},
  {"-%C10-%C11-%O$t%C11$1 %Chas requested to resume %C11$2 %Cfrom %C11$3%C.", 317},
  {"-%C10-%C11-%O$t%C11$1 %Chas offered %C11$2 %C(%C11$3 %Cbytes)", 318},
  {"-%C10-%C11-%O$tReceived '$1%O' from $2", 319},
  {"-%C10-%C11-%O$tNotify: $1 is online ($2).", 320},
  {"-%C10-%C11-%O$t$1 users in notify list.", 321},
  {"-%C10-%C11-%O$tNotify list is empty.", 322},
  {"-%C10-%C11-%O$tNo process is currently running", 323},
  {"-%C10-%C11-%O$tA process is already running", 324},
  {"-%C10-%C11-%O$tLooking up %C11$1%C..", 325},
  {"-%C10-%C11-%O$tConnected.", 326},
  {"-%C10-%C11-%O$tFound your IP: [$1]", 327},
  {"\
-%C10-%C11-%O$tThe file %C11$1%C already exists, saving it as %C11$2%O \
instead.", 328},
  {"%C3>%O$1%C3<%O$tCTCP $2%O", 329},
  {"%C3>%O$1%C3<%O$t$2%O", 330},
  {"%C12-%C13$1/Wallops%C12-%O$t$2%O", 331},
  {"%C08,02 Hostmask             PRIV NOTI CHAN CTCP INVI UNIG %O", 332},
  {" $1 $2  $3  $4  $5  $6  $7", 333},
  {"%C08,02                                                    %O", 334},
  {"%O%C11$1%O added to ignore list.", 335},
  {"%O%C11$1%O removed from ignore list.", 336},
  {"-%C10-%C11-%O$tLooking up IP number for%C11 $1%O..", 337},
  {"  Ignore list is empty.", 338},
  {"Ignore on %C11$1%O changed.", 339},
  {"-%C10-%C11-%O$tNotify: $1 is offline ($2).", 340},
  {"-%C10-%C11-%O$tReceived a malformed DCC request from %C11$1%O.", 341},
  {"-%C10-%C11-%O$tContents of packet: \"$1%O\".", 342},
  {"<%C10-%C11-%O$t$1 %C14(%O$2%C14)%C has left $3 %C14(%O$4%C14)%O", 343},
  {"-%C10-%C11-%O$tYou have left channel $3 %C14(%O$4%C14)%O", 344},
  {"-%C3-%C9-%O$tYou have new mail ($1 messages, $2 bytes total).", 345},
  {"-%C10-%C11-%O$tNo ping reply for $1 seconds, disconnecting.", 346},
  {"-%C10-%C11-%O$tYou're inviting %C11$1%C to %C11$2%C (%C11$3%C)", 347},
  {"-%C10-%C11-%O$t$1 Banlist: %C3$4 %C4$2 %C5$3%O", 348},
  {"%UChannel          Users   Topic%O", 349},
  {"%C08,02 %B-- Notify List --------------- %O", 350},
  {"\
%C8,2 Type  To/From    Status  Size    Pos     File    %O%010%B%\
C9--------------------------------------------------%O", 351},
  {"%C12-%C13$1/$2%C12-%O$t$3%O", 352},
  {"\
Error parsing event %s.\n\
Loading default", 353},
  {"Remote host closed socket", 354},
  {"Connection refused", 355},
  {"No route to host", 356},
  {"Connection timed out", 357},
  {"Cannot assign that address", 358},
  {"Connection reset by peer", 359},
  {"Andorra", 360},
  {"United Arab Emirates", 361},
  {"Afghanistan", 362},
  {"Antigua and Barbuda", 363},
  {"Anguilla", 364},
  {"Albania", 365},
  {"Armenia", 366},
  {"Netherlands Antilles", 367},
  {"Angola", 368},
  {"Antarctica", 369},
  {"Argentina", 370},
  {"American Samoa", 371},
  {"Austria", 372},
  {"Australia", 373},
  {"Aruba", 374},
  {"Azerbaijan", 375},
  {"Bosnia and Herzegovina", 376},
  {"Barbados", 377},
  {"Bangladesh", 378},
  {"Belgium", 379},
  {"Burkina Faso", 380},
  {"Bulgaria", 381},
  {"Bahrain", 382},
  {"Burundi", 383},
  {"Benin", 384},
  {"Bermuda", 385},
  {"Brunei Darussalam", 386},
  {"Bolivia", 387},
  {"Brazil", 388},
  {"Bahamas", 389},
  {"Bhutan", 390},
  {"Bouvet Island", 391},
  {"Botswana", 392},
  {"Belarus", 393},
  {"Belize", 394},
  {"Canada", 395},
  {"Cocos Islands", 396},
  {"Central African Republic", 397},
  {"Congo", 398},
  {"Switzerland", 399},
  {"Cote D'ivoire", 400},
  {"Cook Islands", 401},
  {"Chile", 402},
  {"Cameroon", 403},
  {"China", 404},
  {"Colombia", 405},
  {"Costa Rica", 406},
  {"Former Czechoslovakia", 407},
  {"Cuba", 408},
  {"Cape Verde", 409},
  {"Christmas Island", 410},
  {"Cyprus", 411},
  {"Czech Republic", 412},
  {"Germany", 413},
  {"Djibouti", 414},
  {"Denmark", 415},
  {"Dominica", 416},
  {"Dominican Republic", 417},
  {"Algeria", 418},
  {"Ecuador", 419},
  {"Estonia", 420},
  {"Egypt", 421},
  {"Western Sahara", 422},
  {"Eritrea", 423},
  {"Spain", 424},
  {"Ethiopia", 425},
  {"Finland", 426},
  {"Fiji", 427},
  {"Falkland Islands", 428},
  {"Micronesia", 429},
  {"Faroe Islands", 430},
  {"France", 431},
  {"France, Metropolitan", 432},
  {"Gabon", 433},
  {"Great Britain", 434},
  {"Grenada", 435},
  {"Georgia", 436},
  {"French Guiana", 437},
  {"British Channel Isles", 438},
  {"Ghana", 439},
  {"Gibraltar", 440},
  {"Greenland", 441},
  {"Gambia", 442},
  {"Guinea", 443},
  {"Guadeloupe", 444},
  {"Equatorial Guinea", 445},
  {"Greece", 446},
  {"S. Georgia and S. Sandwich Isles.", 447},
  {"Guatemala", 448},
  {"Guam", 449},
  {"Guinea-Bissau", 450},
  {"Guyana", 451},
  {"Hong Kong", 452},
  {"Heard and McDonald Islands", 453},
  {"Honduras", 454},
  {"Croatia", 455},
  {"Haiti", 456},
  {"Hungary", 457},
  {"Indonesia", 458},
  {"Ireland", 459},
  {"Israel", 460},
  {"India", 461},
  {"British Indian Ocean Territory", 462},
  {"Iraq", 463},
  {"Iran", 464},
  {"Iceland", 465},
  {"Italy", 466},
  {"Jamaica", 467},
  {"Jordan", 468},
  {"Japan", 469},
  {"Kenya", 470},
  {"Kyrgyzstan", 471},
  {"Cambodia", 472},
  {"Kiribati", 473},
  {"Comoros", 474},
  {"St. Kitts and Nevis", 475},
  {"North Korea", 476},
  {"South Korea", 477},
  {"Kuwait", 478},
  {"Cayman Islands", 479},
  {"Kazakhstan", 480},
  {"Laos", 481},
  {"Lebanon", 482},
  {"Saint Lucia", 483},
  {"Liechtenstein", 484},
  {"Sri Lanka", 485},
  {"Liberia", 486},
  {"Lesotho", 487},
  {"Lithuania", 488},
  {"Luxembourg", 489},
  {"Latvia", 490},
  {"Libya", 491},
  {"Morocco", 492},
  {"Monaco", 493},
  {"Moldova", 494},
  {"Madagascar", 495},
  {"Marshall Islands", 496},
  {"Macedonia", 497},
  {"Mali", 498},
  {"Myanmar", 499},
  {"Mongolia", 500},
  {"Macau", 501},
  {"Northern Mariana Islands", 502},
  {"Martinique", 503},
  {"Mauritania", 504},
  {"Montserrat", 505},
  {"Malta", 506},
  {"Mauritius", 507},
  {"Maldives", 508},
  {"Malawi", 509},
  {"Mexico", 510},
  {"Malaysia", 511},
  {"Mozambique", 512},
  {"Namibia", 513},
  {"New Caledonia", 514},
  {"Niger", 515},
  {"Norfolk Island", 516},
  {"Nigeria", 517},
  {"Nicaragua", 518},
  {"Netherlands", 519},
  {"Norway", 520},
  {"Nepal", 521},
  {"Nauru", 522},
  {"Neutral Zone", 523},
  {"Niue", 524},
  {"New Zealand", 525},
  {"Oman", 526},
  {"Panama", 527},
  {"Peru", 528},
  {"French Polynesia", 529},
  {"Papua New Guinea", 530},
  {"Philippines", 531},
  {"Pakistan", 532},
  {"Poland", 533},
  {"St. Pierre and Miquelon", 534},
  {"Pitcairn", 535},
  {"Puerto Rico", 536},
  {"Portugal", 537},
  {"Palau", 538},
  {"Paraguay", 539},
  {"Qatar", 540},
  {"Reunion", 541},
  {"Romania", 542},
  {"Russian Federation", 543},
  {"Rwanda", 544},
  {"Saudi Arabia", 545},
  {"Solomon Islands", 546},
  {"Seychelles", 547},
  {"Sudan", 548},
  {"Sweden", 549},
  {"Singapore", 550},
  {"St. Helena", 551},
  {"Slovenia", 552},
  {"Svalbard and Jan Mayen Islands", 553},
  {"Slovak Republic", 554},
  {"Sierra Leone", 555},
  {"San Marino", 556},
  {"Senegal", 557},
  {"Somalia", 558},
  {"Suriname", 559},
  {"Sao Tome and Principe", 560},
  {"Former USSR", 561},
  {"El Salvador", 562},
  {"Syria", 563},
  {"Swaziland", 564},
  {"Turks and Caicos Islands", 565},
  {"Chad", 566},
  {"French Southern Territories", 567},
  {"Togo", 568},
  {"Thailand", 569},
  {"Tajikistan", 570},
  {"Tokelau", 571},
  {"Turkmenistan", 572},
  {"Tunisia", 573},
  {"Tonga", 574},
  {"East Timor", 575},
  {"Turkey", 576},
  {"Trinidad and Tobago", 577},
  {"Tuvalu", 578},
  {"Taiwan", 579},
  {"Tanzania", 580},
  {"Ukraine", 581},
  {"Uganda", 582},
  {"United Kingdom", 583},
  {"US Minor Outlying Islands", 584},
  {"United States of America", 585},
  {"Uruguay", 586},
  {"Uzbekistan", 587},
  {"Vatican City State", 588},
  {"St. Vincent and the grenadines", 589},
  {"Venezuela", 590},
  {"British Virgin Islands", 591},
  {"US Virgin Islands", 592},
  {"Vietnam", 593},
  {"Vanuatu", 594},
  {"Wallis and Futuna Islands", 595},
  {"Samoa", 596},
  {"Yemen", 597},
  {"Mayotte", 598},
  {"Yugoslavia", 599},
  {"South Africa", 600},
  {"Zambia", 601},
  {"Zaire", 602},
  {"Zimbabwe", 603},
  {"Internic Commercial", 604},
  {"Educational Institution", 605},
  {"Government", 606},
  {"International", 607},
  {"Military", 608},
  {"Internic Network", 609},
  {"Internic Non-Profit Organization", 610},
  {"Old School ARPAnet", 611},
  {"Nato Fiel", 612},
  {"United States Medical", 613},
  {"Reverse DNS", 614},
  {"Unknown", 615},
  {"\
NAME SUB\n\
CMD Direct Client-To-Client\n\
\n\
NAME Send File\n\
CMD /dcc send %s\n\
\n\
NAME Offer Chat\n\
CMD /dcc chat %s\n\
\n\
NAME Abort Chat\n\
CMD /dcc close chat %s\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD CTCP\n\
\n\
NAME Version\n\
CMD /ctcp %s VERSION\n\
\n\
NAME Userinfo\n\
CMD /ctcp %s USERINFO\n\
\n\
NAME Clientinfo\n\
CMD /ctcp %s CLIENTINFO\n\
\n\
NAME Ping\n\
CMD /ping %s\n\
\n\
NAME Time\n\
CMD /ctcp %s TIME\n\
\n\
NAME Finger\n\
CMD /ctcp %s FINGER\n\
\n\
NAME XDCC List\n\
CMD /ctcp %s XDCC LIST\n\
\n\
NAME CDCC List\n\
CMD /ctcp %s CDCC LIST\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD Oper\n\
\n\
NAME Kill this user\n\
CMD /quote KILL %s :die!\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD Mode\n\
\n\
NAME Give Voice\n\
CMD /voice %s\n\
\n\
NAME Take Voice\n\
CMD /devoice %s\n\
NAME SEP\n\
CMD \n\
\n\
NAME Give Ops\n\
CMD /op %s\n\
\n\
NAME Take Ops\n\
CMD /deop %s\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD Ignore\n\
\n\
NAME Ignore User\n\
CMD /ignore %s!*@* ALL\n\
\n\
NAME UnIgnore User\n\
CMD /unignore %s!*@*\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD Kick/Ban\n\
\n\
NAME Kick\n\
CMD /kick %s\n\
\n\
NAME Ban\n\
CMD /ban %s\n\
\n\
NAME SEP\n\
CMD \n\
\n\
NAME Ban *!*@*.host\n\
CMD /ban %s 0\n\
\n\
NAME Ban *!*@domain\n\
CMD /ban %s 1\n\
\n\
NAME Ban *!*user@*.host\n\
CMD /ban %s 2\n\
\n\
NAME Ban *!*user@domain\n\
CMD /ban %s 3\n\
\n\
NAME SEP\n\
CMD \n\
\n\
NAME KickBan *!*@*.host\n\
CMD /kickban %s 0\n\
\n\
NAME KickBan *!*@domain\n\
CMD /kickban %s 1\n\
\n\
NAME KickBan *!*user@*.host\n\
CMD /kickban %s 2\n\
\n\
NAME KickBan *!*user@domain\n\
CMD /kickban %s 3\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD Info\n\
\n\
NAME Who\n\
CMD /quote WHO %s\n\
\n\
NAME Whois\n\
CMD /quote WHOIS %s\n\
\n\
NAME DNS Lookup\n\
CMD /dns %s\n\
\n\
NAME Trace\n\
CMD /quote TRACE %s\n\
\n\
NAME UserHost\n\
CMD /quote USERHOST %s\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD External\n\
\n\
NAME Traceroute\n\
CMD !rxvt -e /bin/sh -c \"/usr/sbin/traceroute %h ; sleep 30\"\n\
\n\
NAME Ping\n\
CMD !rxvt -e /bin/sh -c \"ping -c 4 %h ; sleep 30\"\n\
\n\
NAME Telnet\n\
CMD !rxvt -e telnet %h\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME Open Query\n\
CMD /query %s\n\
\n", 616},
  {"\
NAME Op\n\
CMD /op %a\n\
\n\
NAME DeOp\n\
CMD /deop %a\n\
\n\
NAME Ban\n\
CMD /ban %s\n\
\n\
NAME Kick\n\
CMD /kick %s\n\
\n\
NAME Sendfile\n\
CMD /dcc send %s\n\
\n\
NAME Dialog\n\
CMD /query %s\n\
\n", 617},
  {"\
NAME Whois\n\
CMD /whois %s\n\
\n\
NAME Send\n\
CMD /dcc send %s\n\
\n\
NAME Chat\n\
CMD /dcc chat %s\n\
\n\
NAME Ping\n\
CMD /ping %s\n\
\n\
NAME Clear\n\
CMD /clear\n\
\n", 618},
  {"\
NAME SUB\n\
CMD IRC Stuff\n\
\n\
NAME Disconnect\n\
CMD /discon\n\
\n\
NAME Reconnect\n\
CMD /reconnect\n\
\n\
NAME Part Channel\n\
CMD /part\n\
\n\
NAME Cycle Channel\n\
CMD /cycle\n\
\n\
NAME Server Map\n\
CMD /quote MAP\n\
\n\
NAME Server Links\n\
CMD /quote LINKS\n\
\n\
NAME Ping Server\n\
CMD /ping\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD Connect\n\
\n\
NAME irc.xchat.org #Linux\n\
CMD /servchan irc.xchat.org 6667 #linux\n\
\n\
NAME Go to EFNet\n\
CMD /newserver irc.efnet.net\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD Settings\n\
\n\
NAME TOGGLE Hide Version\n\
CMD hide_version\n\
\n\
NAME TOGGLE Colored Nicks\n\
CMD colorednicks\n\
\n\
NAME TOGGLE 1.4.x Nick Comp.\n\
CMD old_nickcompletion\n\
\n\
NAME TOGGLE Strip mIRC color\n\
CMD stripcolor\n\
\n\
NAME TOGGLE Filter Beeps\n\
CMD filterbeep\n\
\n\
NAME TOGGLE Raw MODE Display\n\
CMD raw_modes\n\
\n\
NAME TOGGLE Perl Warnings\n\
CMD perlwarnings\n\
\n\
NAME TOGGLE Mail Checker\n\
CMD mail_check\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD External\n\
\n\
NAME Run XMMS\n\
CMD !xmms\n\
\n\
NAME Run RXVT\n\
CMD !rxvt\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n", 619},
  {"\
NAME SUB\n\
CMD Netscape...\n\
\n\
NAME Open in existing\n\
CMD !netscape -remote 'openURL(%s)'\n\
\n\
NAME Open in new window\n\
CMD !netscape -remote 'openURL(%s,new-window)'\n\
\n\
NAME Run new Netscape\n\
CMD !netscape %s\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD Mozilla...\n\
\n\
NAME Open in existing\n\
CMD !mozilla -remote 'openURL(%s)'\n\
\n\
NAME Open in new window\n\
CMD !mozilla -remote 'openURL(%s,new-window)'\n\
\n\
NAME Run new Mozilla\n\
CMD !mozilla %s\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD Galeon...\n\
\n\
NAME Open in existing\n\
CMD !galeon -x '%s'\n\
\n\
NAME Open in new window\n\
CMD !galeon -w '%s'\n\
\n\
NAME Open in new tab\n\
CMD !galeon -n '%s'\n\
\n\
NAME Run new Galeon\n\
CMD !galeon '%s'\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD Opera...\n\
\n\
NAME Open in existing\n\
CMD !opera -remote 'openURL(%s)'\n\
\n\
NAME Open in new window\n\
CMD !opera -remote 'openURL(%s,new-window)'\n\
\n\
NAME Run new Opera\n\
CMD !opera %s\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME SUB\n\
CMD Send URL to...\n\
\n\
NAME Gnome URL Handler\n\
CMD !gnome-moz-remote %s\n\
\n\
NAME Lynx\n\
CMD !rxvt -e lynx %s\n\
\n\
NAME Links\n\
CMD !rxvt -e links %s\n\
\n\
NAME w3m\n\
CMD !rxvt -e w3m %s\n\
\n\
NAME NcFTP\n\
CMD !rxvt -e ncftp %s\n\
\n\
NAME gFTP\n\
CMD !gftp %s\n\
\n\
NAME Konqueror\n\
CMD !konqueror %s\n\
\n\
NAME Telnet\n\
CMD !rxvt -e telnet %s\n\
\n\
NAME Ping\n\
CMD !rxvt -e ping -c 4 %s\n\
\n\
NAME ENDSUB\n\
CMD \n\
\n\
NAME Connect as IRC server\n\
CMD /newserver %s\n\
\n", 620},
  {"\
An IRC Client for UNIX.\n\
\n\
This binary was compiled on ", 621},
  {"\
\n\
Using GTK %d.%d.%d X %d\n\
Running on %s", 622},
  {"About X-Chat", 623},
  {"\
(C) 1998-2001 Peter Zelezny <zed@xchat.org>\n\
\n\
An IRC Client for UNIX.\n\
\n\
This binary was compiled on ", 624},
  {"\
\n\
Using GTK %d.%d.%d X %d\n\
Running on %s\n", 625},
  {"Ascii Chart", 626},
  {"User and Channel Statistics: %d/%d Users on %d/%d Channels", 627},
  {"I can't save an empty list!", 628},
  {"Select an output filename", 629},
  {"X-Chat: Channel List (%s)", 630},
  {"List display options:", 631},
  {"Minimum Users: ", 632},
  {"Maximum Users: ", 633},
  {"Regex Match: ", 634},
  {" Apply ", 635},
  {"Refresh the list", 636},
  {"Save the list", 637},
  {"Join Channel", 638},
  {"Send file to %s", 639},
  {"\
      File: %s\n\
   To/From: %s\n\
      Size: %d\n\
      Port: %d\n\
 IP Number: %s\n\
Start Time: %s", 640},
  {"Status", 641},
  {"File", 642},
  {"ETA", 643},
  {"From", 644},
  {"MIME Type", 645},
  {"X-Chat: File Receive List", 646},
  {"Accept", 647},
  {"Resume", 648},
  {"Abort", 649},
  {"Info", 650},
  {"Open", 651},
  {"Ack", 652},
  {"To", 653},
  {"X-Chat: File Send List", 654},
  {"To/From", 655},
  {"Recv", 656},
  {"Sent", 657},
  {"StartTime", 658},
  {"X-Chat: DCC Chat List", 659},
  {"*NEW*", 660},
  {"EDIT ME", 661},
  {"Name", 662},
  {"Command", 663},
  {"Move Up", 664},
  {"Move Dn", 665},
  {"Cancel", 666},
  {"Save", 667},
  {"Add New", 668},
  {"Delete", 669},
  {"Sort", 670},
  {"Help", 671},
  {"Config dir", 672},
  {"Don't Auto connect", 673},
  {"Don't use GNOME Panel", 674},
  {"\
%s %s Options:\n\
\n\
   --cfgdir <dir> -d\t : use a different config dir\n\
   --noauto       -a\t : don't auto connect\n\
   --version      -v\t : show version information\n", 675},
  {"\
Cannot open font:\n\
\n\
%s", 676},
  {"gdk_font_load failed", 677},
  {"Topic for %s is: %s", 678},
  {"The Run Command action runs the data in Data 1 as if it has been typed into the entry box where you pressed the key sequence. Thus it can contain text (which will be sent to the channel/person), commands or user commands. When run all \\n characters in Data 1 are used to deliminate seperate commands so it is possible to run more than one command. If you want a \\ in the actual text run then enter \\\\", 679},
  {"The Change Page command switches between pages in the notebook. Set Data 1 to the page you want to switch to. If Data 2 is set to anything then the switch will be relative to the current position", 680},
  {"The Insert in Buffer command will insert the contents of Data 1 into the entry where the key sequence was pressed at the current cursor position", 681},
  {"The Scroll Page command scrolls the text widget up or down one page. If Data 1 is set to anything the page scrolls up, else it scrolls down", 682},
  {"The Set Buffer command sets the entry where the key sequence was entered to the contents of Data 1", 683},
  {"The Last Command command sets the entry to contain the last command entered - the same as pressing up in a shell", 684},
  {"The Next Command command sets the entry to contain the next command entered - the same as pressing down in a shell", 685},
  {"\
This command changes the text in the entry to finish an incomplete nickname \
or command. If Data 1 is set then double-tabbing in a string will select the \
last nick, not the next", 686},
  {"\
This command scrolls up and down through the list of nicks. If Data 1 is set \
to anything it will scroll up, else it scrolls down", 687},
  {"\
This command checks the last work entered in the entry against the replace \
list and replaces it if it finds a match", 688},
  {"This command move the front tab left by one", 689},
  {"This command move the front tab right by one", 690},
  {"Push input line into history but doesn't send to server", 691},
  {"There was an error loading key bindings configuration", 692},
  {"<none>", 693},
  {"Mod", 694},
  {"Key", 695},
  {"Action", 696},
  {"X-Chat: Edit Key Bindings", 697},
  {"Add new", 698},
  {"Shift", 699},
  {"Alt", 700},
  {"Ctrl", 701},
  {"Data 1", 702},
  {"Data 2", 703},
  {"Error opening keys config file\n", 704},
  {"\
Unknown keyname %s in key bindings config file\n\
Load aborted, please fix ~/.xchat/keybindings.conf\n", 705},
  {"\
Unknown action %s in key bindings config file\n\
Load aborted, Please fix ~/.xchat/keybindings\n", 706},
  {"\
Expecting Data line (beginning Dx{:|!}) but got:\n\
%s\n\
\n\
Load aborted, Please fix ~/.xchat/keybindings\n", 707},
  {"Ok", 708},
  {"Cannot write to that file.", 709},
  {"Cannot read that file.", 710},
  {"Yes", 711},
  {"No", 712},
  {"new!new@new.com", 713},
  {"Mask", 714},
  {"CTCP", 715},
  {"Private", 716},
  {"Chan", 717},
  {"Notice", 718},
  {"Invite", 719},
  {"Unignore", 720},
  {"X-Chat: Ignore list", 721},
  {"Ignore Mask:", 722},
  {"Ignore Stats:", 723},
  {"CTCP:", 724},
  {"Private:", 725},
  {"Channel:", 726},
  {"Notice:", 727},
  {"Invite:", 728},
  {"OK", 729},
  {"New", 730},
  {"The channel topic", 731},
  {"User limit must be a number!\n", 732},
  {"Open Toolbox", 733},
  {"Close Toolbox", 734},
  {"Beep", 735},
  {"Beep on messages", 736},
  {"Conf", 737},
  {"Conference mode (no join/part msgs)", 738},
  {"CP", 739},
  {"Color Paste", 740},
  {"Ascii", 741},
  {"Open ASCII Chart", 742},
  {"Underline", 743},
  {"Bold", 744},
  {"Plain Text", 745},
  {"Hide/Show Userlist", 746},
  {"Keyword", 747},
  {"User Limit", 748},
  {"Ban List", 749},
  {"Moderated", 750},
  {"Invite Only", 751},
  {"Secret", 752},
  {"No outside messages", 753},
  {"Topic Protection", 754},
  {"Host unknown", 755},
  {"User: %s", 756},
  {"Country: %s", 757},
  {"Realname: %s", 758},
  {"Server: %s", 759},
  {"Last Msg: %s", 760},
  {"Menu Bar", 761},
  {"Topic Bar", 762},
  {"User List", 763},
  {"Part Channel", 764},
  {"Cycle Channel", 765},
  {"\
*WARNING*\n\
Auto accepting DCC to your home directory\n\
can be dangerous and is exploitable. Eg:\n\
Someone could send you a .bash_profile", 766},
  {"Settings saved.", 767},
  {"Select a Perl script to load", 768},
  {"Select a Plugin to load", 769},
  {"Select a Python script to load", 770},
  {"\
User Commands - Special codes:\n\
\n\
%c  =  current channel\n\
%m  =  machine info\n\
%n  =  your nick\n\
%t  =  time/date\n\
%v  =  x-chat version (", 771},
  {"\
)\n\
%2  =  word 2\n\
%3  =  word 3\n\
&2  =  word 2 to the end of line\n\
&3  =  word 3 to the end of line\n\
\n\
eg:\n\
/cmd john hello\n\
\n\
%2 would be \"john\"\n\
&2 would be \"john hello\".", 772},
  {"\
Userlist Popup - Special codes:\n\
\n\
%c  =  current channel\n\
%h  =  selected nick's hostname\n\
%m  =  machine info\n\
%n  =  your nick\n\
%s  =  selected nick\n\
%t  =  time/date\n", 773},
  {"\
Userlist Buttons - Special codes:\n\
\n\
%a  =  all selected nicks\n\
%c  =  current channel\n\
%h  =  selected nick's hostname\n\
%m  =  machine info\n\
%n  =  your nick\n\
%s  =  selected nick\n\
%t  =  time/date\n", 774},
  {"\
Dialog Buttons - Special codes:\n\
\n\
%a  =  all selected nicks\n\
%c  =  current channel\n\
%h  =  selected nick's hostname\n\
%m  =  machine info\n\
%n  =  your nick\n\
%s  =  selected nick\n\
%t  =  time/date\n", 775},
  {"\
CTCP Replies - Special codes:\n\
\n\
%d  =  data (the whole ctcp)\n\
%m  =  machine info\n\
%s  =  nick who sent the ctcp\n\
%t  =  time/date\n\
%2  =  word 2\n\
%3  =  word 3\n\
&2  =  word 2 to the end of line\n\
&3  =  word 3 to the end of line\n\
\n", 776},
  {"\
URL Handlers - Special codes:\n\
\n\
%s  =  the URL string\n\
\n\
Putting a ! infront of the command\n\
indicates it should be sent to a\n\
shell instead of X-Chat", 777},
  {"X-Chat: User Defined Commands", 778},
  {"X-Chat: Userlist Popup menu", 779},
  {"X-Chat: Replace", 780},
  {"X-Chat: User menu", 781},
  {"X-Chat: URL Handlers", 782},
  {"X-Chat: Userlist buttons", 783},
  {"X-Chat: Dialog buttons", 784},
  {"X-Chat: CTCP Replies", 785},
  {"Server List..", 786},
  {"New Server Tab..", 787},
  {"New Server Window..", 788},
  {"New Channel Tab..", 789},
  {"New Channel Window..", 790},
  {"New Shell Tab..", 791},
  {"Close", 792},
  {"Quit", 793},
  {"Channel List Window..", 794},
  {"File Send Window..", 795},
  {"File Receive Window..", 796},
  {"DCC Chat Window..", 797},
  {"Raw Log Window..", 798},
  {"URL Grabber Window..", 799},
  {"Notify List Window..", 800},
  {"Ban List Window..", 801},
  {"Ignore Window..", 802},
  {"Flush Buffer", 803},
  {"Search Buffer..", 804},
  {"Save Buffer..", 805},
  {"Invisible", 806},
  {"Receive Wallops", 807},
  {"Receive Server Notices", 808},
  {"Marked Away", 809},
  {"Auto Rejoin on Kick", 810},
  {"Auto ReConnect to Server", 811},
  {"Never-give-up ReConnect", 812},
  {"Auto Open Dialog Windows", 813},
  {"Auto Accept DCC Chat", 814},
  {"Auto Accept DCC Send", 815},
  {"Setup..", 816},
  {"Palette..", 817},
  {"User Commands..", 818},
  {"CTCP Replies..", 819},
  {"Userlist Buttons..", 820},
  {"Userlist Popup..", 821},
  {"Dialog Buttons..", 822},
  {"Replace Popup..", 823},
  {"URL Handlers..", 824},
  {"Edit Event Texts..", 825},
  {"Edit Key Bindings..", 826},
  {"Reload Settings", 827},
  {"Save Settings now", 828},
  {"Save Settings on exit", 829},
  {"X-Chat Homepage..", 830},
  {"Online Docs..", 831},
  {"About X-Chat..", 832},
  {"Perl Script..", 833},
  {"Python Script..", 834},
  {"Plugin..", 835},
  {"Perl List", 836},
  {"Python List", 837},
  {"Plugin List", 838},
  {"All Perl Scripts", 839},
  {"All Python Scripts", 840},
  {"All Plugins", 841},
  {"Load", 842},
  {"Kill", 843},
  {"Edit User Menu..", 844},
  {"_X-Chat", 845},
  {"_Windows", 846},
  {"User _Modes", 847},
  {"_Settings", 848},
  {"S_cripts & Plugins", 849},
  {"Use_r Menu", 850},
  {"_Help", 851},
  {"X-Chat", 852},
  {"Windows", 853},
  {"User Modes", 854},
  {"Auto ReJoin on Kick", 855},
  {"Settings", 856},
  {"Replace..", 857},
  {"Scripts & Plugins", 858},
  {"Load Perl Script..", 859},
  {"Unload All Scripts", 860},
  {"Load Plugin (*.so)..", 861},
  {"Unload All Plugins", 862},
  {"Load Python Script..", 863},
  {"User Menu", 864},
  {"Edit User Menu", 865},
  {"Offline", 866},
  {"Never", 867},
  {"Online", 868},
  {"Use the /NOTIFY command to add people to your notify list.", 869},
  {"User", 870},
  {"Server", 871},
  {"Last Seen", 872},
  {"X-Chat: Notify List", 873},
  {"Add", 874},
  {"Remove", 875},
  {"Select color", 876},
  {"X-Chat: Palette", 877},
  {"Foreground", 878},
  {"Background", 879},
  {"Mark Background", 880},
  {"Mark Foreground", 881},
  {"Color %d", 882},
  {"About...", 883},
  {"No Channel", 884},
  {"No Server", 885},
  {"Is Tab", 886},
  {"Is Not Tab", 887},
  {"Hide", 888},
  {"Show", 889},
  {"Move Here", 890},
  {"View", 891},
  {"Description", 892},
  {"X-Chat Plugins", 893},
  {"Unload", 894},
  {"Save rawlog", 895},
  {"X-Chat: Rawlog (%s) [alt-s to save]", 896},
  {"The window you opened this Search for doesn't exist anymore.", 897},
  {"X-Chat: Search", 898},
  {"Find:", 899},
  {"Find", 900},
  {"Clear", 901},
  {"X-Chat: Edit entry", 902},
  {"Edit entry:", 903},
  {"Name:", 904},
  {"Server:", 905},
  {"Port:", 906},
  {"Password:", 907},
  {"Channels:", 908},
  {"Nickname:", 909},
  {"Connect Cmd:", 910},
  {"Command to execute after the connection is complete", 911},
  {"Autoconnect", 912},
  {"Use Proxy", 913},
  {"Use proxy server if one is set in Setup->Proxy Server", 914},
  {"Use SSL", 915},
  {"Accept invalid cert.", 916},
  {"New Server", 917},
  {"New Group", 918},
  {"\
Cannot use \"root\" as a nickname,\n\
please change that first.", 919},
  {"X-Chat: Server List", 920},
  {"User info:", 921},
  {"Nicknames:", 922},
  {"Realname:", 923},
  {"Username:", 924},
  {"Connect New", 925},
  {"Edit", 926},
  {"Skip MOTD", 927},
  {"Don't display the message-of-the-day when logging in", 928},
  {"Show channels", 929},
  {"No ServerList on startup", 930},
  {"Browse...", 931},
  {"Choose File", 932},
  {"Select Font", 933},
  {"Failed to load translation table.", 934},
  {"\
The following prefs do not take effect\n\
immediately, you will have to close the\n\
window and re-open it:\n\
\n\
 - Channel Tabs\n\
 - Channel Mode Buttons\n\
 - Userlist Buttons\n\
 - Disable Paned Userlist\n\
 - Notify User color\n\
 - Layout for a vertical panel\n\
 - Auto Indent", 935},
  {"Appearance", 936},
  {"Font:", 937},
  {"Background Picture:", 938},
  {"Background XPM:", 939},
  {"Indent Nicks", 940},
  {"Make nicknames right justified.", 941},
  {"Auto Indent", 942},
  {"Auto adjust the separator bar position as needed.", 943},
  {"Draw Separator Bar", 944},
  {"Make the separator an actual visible line.", 945},
  {"Word Wrap", 946},
  {"Don't split words from one line to the next", 947},
  {"Transparent Background", 948},
  {"Make the text box seem see-through", 949},
  {"Tint Transparency", 950},
  {"Tint the see-through text box to make it darker", 951},
  {"Use a font set", 952},
  {"Tint Setting", 953},
  {"Change in realtime", 954},
  {"Red:", 955},
  {"Green:", 956},
  {"Blue:", 957},
  {"A-Z, Ops first", 958},
  {"A-Z", 959},
  {"Z-A, Ops last", 960},
  {"Z-A", 961},
  {"Unsorted", 962},
  {"Startup and Shutdown", 963},
  {"No Server List On Startup", 964},
  {"Don't display the server list on X-Chat startup", 965},
  {"Auto Save URL list", 966},
  {"Auto save your URL list when exiting from X-Chat", 967},
  {"Give the User List style", 968},
  {"Show userhost", 969},
  {"Show userhost of users in channel userlist", 970},
  {"Enable Paned Userlist", 971},
  {"Use paned user list instead of a fixed width one", 972},
  {"Userlist icons", 973},
  {"Double Click Command:", 974},
  {"Userlist sorted by:", 975},
  {"Input Box", 976},
  {"Nick Name Completion", 977},
  {"Complete nicknames when a partial one is entered", 978},
  {"Old-style Nickname Completion", 979},
  {"Nickname completion is old-style (instead of GNU-style)", 980},
  {"Give the Input Box style", 981},
  {"Input box gets same style as main text area", 982},
  {"Input Box always in focus", 983},
  {"Show nickname", 984},
  {"Show nickname and op/voice icon before the input box", 985},
  {"Nickname Completion Character:", 986},
  {"Character to append to completed nicknames", 987},
  {"Output Box", 988},
  {"Strip MIRC Color", 989},
  {"Strip MIRC color codes from text before displaying", 990},
  {"Colored Nicks", 991},
  {"Output nicknames in different colors", 992},
  {"Show invites in active window", 993},
  {"Time Stamp All Text", 994},
  {"Prefix all text with the current time stamp", 995},
  {"Filter out BEEPs", 996},
  {"Remove ^G BEEP codes from text before displaying", 997},
  {"Time Stamp Format:", 998},
  {"Buffer Settings", 999},
  {"Text Buffer Size:", 1000},
  {"lines (0=Unlimited).", 1001},
  {"Other Settings", 1002},
  {"Kanji locale <=> JIS translation", 1003},
  {"Bottom", 1004},
  {"Top", 1005},
  {"Left", 1006},
  {"Right", 1007},
  {"Hidden", 1008},
  {"Off", 1009},
  {"Progress bar", 1010},
  {"Info text", 1011},
  {"Both", 1012},
  {"Buttons", 1013},
  {"Channel Mode Buttons", 1014},
  {"Show the TNSIPMLK buttons", 1015},
  {"User List Buttons", 1016},
  {"Show the buttons below the user list", 1017},
  {"Meters", 1018},
  {"Lag meter:", 1019},
  {"Throttle meter:", 1020},
  {"Tabs", 1021},
  {"Tabs Located at:", 1022},
  {"Channel Tabs", 1023},
  {"Use tabs for channels instead of separate windows", 1024},
  {"Limited Tab Highlighting", 1025},
  {"Only highlight channel tabs for channel messages and actions", 1026},
  {"New Tabs to front", 1027},
  {"Bring new query/channel tabs to front", 1028},
  {"Private Message Tabs", 1029},
  {"Use tabs for /query instead of separate windows", 1030},
  {"Use a separate tab/window for server messages", 1031},
  {"Use a separate tab/window for notices and server notices", 1032},
  {"Use tabs for DCC, Ignore, Notify etc windows.", 1033},
  {"Window Position", 1034},
  {"\
If Left and Top are set to zero, X-Chat will use\n\
your window manager defaults.", 1035},
  {"Left:", 1036},
  {"Top:", 1037},
  {"Window Size", 1038},
  {"Width:", 1039},
  {"Height:", 1040},
  {"Show Session Tree View", 1041},
  {"General", 1042},
  {"Hide Session on Panelize", 1043},
  {"Hide X-Chat when window moved to the panel", 1044},
  {"Panel Applet", 1045},
  {"Layout For a Vertical Panel", 1046},
  {"Layout the X-Chat panel applet for a vertical panel", 1047},
  {"Raw Mode Display", 1048},
  {"Display raw mode changes instead of interpretations", 1049},
  {"Beep on Private Messages", 1050},
  {"Beep when a private message for you is received", 1051},
  {"Beep on Channel Messages", 1052},
  {"Beep when a channel message is received", 1053},
  {"Send /who #chan on join.", 1054},
  {"Find user information when joining a channel.", 1055},
  {"Perform a periodic mail check.", 1056},
  {"Your irc settings", 1057},
  {"Quit Message:", 1058},
  {"Part Message:", 1059},
  {"\
These can be a filename relative to ~/.xchat/ to be\n\
used as a list of random quit or part reasons.", 1060},
  {"External Programs", 1061},
  {"DNS Lookup Program:", 1062},
  {"Timing", 1063},
  {"Auto ReConnect Delay:", 1064},
  {"seconds.", 1065},
  {"Address", 1066},
  {"Hostname / IP Number:", 1067},
  {"\
Most people should leave this blank, it's only\n\
usefull for machines with multiple addresses.", 1068},
  {"Public IP Address", 1069},
  {"DCC IP Address:", 1070},
  {"\
You may need to set the DCC IP Address if\n\
you're behind a NAT router or proxy firewall.", 1071},
  {"Get my IP from Server (for use in DCC Send only)", 1072},
  {"For people using a 10.* or 192.168.* IP number.", 1073},
  {"(Disabled)", 1074},
  {"Wingate", 1075},
  {"Socks4", 1076},
  {"Socks5", 1077},
  {"HTTP", 1078},
  {"Proxy Server Hostname:", 1079},
  {"Proxy Server Port:", 1080},
  {"Proxy Type:", 1081},
  {"Show away once", 1082},
  {"Only show away messages the first time they're seen", 1083},
  {"Announce away messages", 1084},
  {"Announce your away message to the channel(s) you are in", 1085},
  {"Automatic unmark away", 1086},
  {"When typing is started, the away flag is unset", 1087},
  {"Your away settings", 1088},
  {"Away Reason:", 1089},
  {"Words to Highlight:", 1090},
  {"(separate with commas)", 1091},
  {"Logging", 1092},
  {"Enable logging conversations to disk", 1093},
  {"Always timestamp logs", 1094},
  {"Always apply timestamp to disk logs", 1095},
  {"Log name mask:", 1096},
  {"Log timestamp format:", 1097},
  {"Generic", 1098},
  {"Show notifies in active window", 1099},
  {"Send /whois", 1100},
  {"User List Notify Highlighting", 1101},
  {"Highlight Notifies", 1102},
  {"Highlight notified users in the user list", 1103},
  {"Notified User Color:", 1104},
  {"Notification Timeouts", 1105},
  {"Notify Check Interval:", 1106},
  {"seconds (0=Disable).", 1107},
  {"Enable Character Translation", 1108},
  {"Translation File:", 1109},
  {"Use a ircII style translation file.", 1110},
  {"Auto Open DCC Send Window", 1111},
  {"Automatically open DCC Send Window", 1112},
  {"Auto Open DCC Recv Window", 1113},
  {"Automatically open DCC Recv Window", 1114},
  {"Auto Open DCC Chat Window", 1115},
  {"Automatically open DCC Chat Window", 1116},
  {"Resume on Auto Accept", 1117},
  {"When Auto-Accepting DCC, try to resume.", 1118},
  {"Timeouts", 1119},
  {"DCC Offers Timeout:", 1120},
  {"DCC Stall Timeout:", 1121},
  {"Received files", 1122},
  {"File Permissions:", 1123},
  {"(octal)", 1124},
  {"Directory to save to:", 1125},
  {"Save file with Nickname", 1126},
  {"Put the sender's nickname in incoming filenames", 1127},
  {"DCC Send Options", 1128},
  {"Fast DCC Send", 1129},
  {"Don't wait for ACKs to send more data", 1130},
  {"Fill Spaces", 1131},
  {"File names with spaces will be filled with underscore", 1132},
  {"First DCC Send Port:", 1133},
  {"(0=Disabled)", 1134},
  {"Last DCC Send Port:", 1135},
  {"Send Block Size:", 1136},
  {"(1024=Normal)", 1137},
  {"Built-in Replies", 1138},
  {"Hide Version", 1139},
  {"Do not reply to CTCP version", 1140},
  {"Sound", 1141},
  {"Sound Dir:", 1142},
  {"Play Command:", 1143},
  {"X-Chat: Preferences", 1144},
  {"Apply", 1145},
  {"Categories", 1146},
  {"Interface Settings", 1147},
  {"Interface", 1148},
  {"IRC Input/Output Settings", 1149},
  {"IRC Input/Output", 1150},
  {"Window Layout Settings", 1151},
  {"Window Layout", 1152},
  {"Main Window Settings", 1153},
  {"Main Window", 1154},
  {"Channel Window Settings", 1155},
  {"Channel Windows", 1156},
  {"Dialog Window Settings", 1157},
  {"Dialog Windows", 1158},
  {"Panel Settings", 1159},
  {"Panel", 1160},
  {"IRC Settings", 1161},
  {"IRC", 1162},
  {"IP Address Settings", 1163},
  {"IP Address", 1164},
  {"Proxy Server", 1165},
  {"Away Settings", 1166},
  {"Away", 1167},
  {"Highlighting Settings", 1168},
  {"Highlighting", 1169},
  {"Logging Settings", 1170},
  {"Notification Settings", 1171},
  {"Notification", 1172},
  {"Character Set (Translation Tables)", 1173},
  {"Character Set", 1174},
  {"CTCP Settings", 1175},
  {"DCC Settings", 1176},
  {"DCC", 1177},
  {"File Transfer Settings", 1178},
  {"File Transfer", 1179},
  {"There was an error parsing the string", 1180},
  {"This signal is only passed %d args, $%d is invalid", 1181},
  {"Print Texts File", 1182},
  {"Event", 1183},
  {"$ Number", 1184},
  {"Edit Events", 1185},
  {"Sound file: ", 1186},
  {"Save As", 1187},
  {"Load From", 1188},
  {"Test All", 1189},
  {"Select a file to save to", 1190},
  {"X-Chat: URL Grabber", 1191},
};

int _msg_tbl_length = 1191;
